[package]
name = "lapc-codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
lapc-ir = { path = "../lapc-ir" }
lapc-extern = { path = "../lapc-extern" }

[dev-dependencies]
lapc-ast = { path = "../lapc-ast" }
lapc-parse = { path = "../lapc-parse" }
lapc-check = { path = "../lapc-check" }
lapc-erase = { path = "../lapc-erase" }
